apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager:v1.9.1
  namespace: openshift-operators
  labels:
    usage: development
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: cert-manager:v1.9.1
  source: community-operators
  sourceNamespace: openshift-marketplace
